version: 2.1
jobs:
  compile:
   docker:
      - image: djemil/myrdp:latest
   steps:
      - run:
          command: |
           apt install --assume-yes git
           watch -n5 time

workflows:
  version: 2.1
  cooking:
    jobs:
      - compile